on:
  push:
      branches:
      - production

name: ðŸš€ Deploy website to production
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy to production
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: linux168.unoeuro.com
        username: odensedansecent.dk
        password: ${{ secrets.odc_ftp_password }}
        server-dir: /laravel/
